export default Object({
  id: '',
  key: '',
  status: 'new',
  caption: '',
  userheaderData: "YangTian",
  days: '',
  time: {
    start: {
      key: 'start',
      headerData: '时间',
      inputData: '',
      errorMark: false,
      show: true,
    },
  },
  base: {
    startStore: {
      key: 'startStore',
      headerData: '已存',
      inputData: '',
      errorMark: false,
      show: false,
    },
    startFund: {
      key: 'startFund',
      headerData: '理财',
      inputData: '',
      errorMark: false,
      show: true,
    },
  },
  income: {
    monthlyIncome: {
      key: 'monthlyIncome',
      headerData: '工资',
      inputData: '',
      errorMark: false,
      show: true,
    },
    bonus: {
      key: 'bonus',
      headerData: '奖金',
      inputData: '',
      errorMark: false,
      show: true,
    },
  },
  expense: {
    monthlyExpense: {
      saveMoney: {
        key: 'saveMoney',
        headerData: "存款",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      china: {
        key: 'china',
        headerData: "回国",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      tourism: {
        key: 'tourism',
        headerData: "旅游",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      fund: {
        key: 'fund',
        headerData: "投资",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      house: {
        key: 'house',
        headerData: "房子",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      iphone: {
        key: 'iphone',
        headerData: "手机",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      food: {
        key: 'food',
        headerData: "吃的",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      demonCost: {
        key: 'demonCost',
        headerData: "烟酒",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      traffic: {
        key: 'traffic',
        headerData: "交通",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      growUp: {
        key: 'growUp',
        headerData: "成长",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      happy: {
        key: 'happy',
        headerData: "娱乐",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
      others: {
        key: 'others',
        headerData: "其他",
        inputData: '',
        errorMark: false,
        nowData: '0',
        show: true,
      },
    }
  }
})

